from selenium.webdriver.common.by import By
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import SleepTimingType
from src.testproject.sdk.drivers import webdriver
import pytest


"""
This pytest test was automatically generated by TestProject
    Project: My first Project
    Package: TestProject.Generated.Tests.MyFirstProject
    Test: CP-3
    Generated by: David Stiven leon (ldavidz1999@gmail.com)
    Generated on 04/12/2021, 07:05:20
"""


@pytest.fixture()
def driver():
    driver = webdriver.Chrome(token="PSc4r5iDlXSHMibj4jOOkVAqcnPHQniWynK3ymF4xf8",
                              project_name="My first Project",
                              job_name="CP-3")
    step_settings = StepSettings(timeout=15000,
                                 sleep_time=500,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):
    """Modificar Usuario."""
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "https://example.testproject.io/web/"

    # 1. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(f'{ApplicationURL}')

    # 2. Navigate to 'https://idiv-cloud.webcindario.com/'
    driver.get("https://idiv-cloud.webcindario.com/")

    # 3. Click 'Iniciar Sesion1'
    iniciar_sesion1 = driver.find_element(By.XPATH,
                                          "//span[. = 'Iniciar Sesion']")
    iniciar_sesion1.click()

    # 4. Click 'login_nickname_usuario'
    login_nickname_usuario = driver.find_element(By.CSS_SELECTOR,
                                                 "#login_nickname_usuario")
    login_nickname_usuario.click()

    # 5. Type 'prc1' in 'login_nickname_usuario'
    login_nickname_usuario = driver.find_element(By.CSS_SELECTOR,
                                                 "#login_nickname_usuario")
    login_nickname_usuario.send_keys("prc1")

    # 6. Click 'login_contrasena_usuario'
    login_contrasena_usuario = driver.find_element(By.CSS_SELECTOR,
                                                   "#login_contrasena_usuario")
    login_contrasena_usuario.click()

    # 7. Type '123456789' in 'login_contrasena_usuario'
    login_contrasena_usuario = driver.find_element(By.CSS_SELECTOR,
                                                   "#login_contrasena_usuario")
    login_contrasena_usuario.send_keys("123456789")

    # 8. Click 'INPUT'
    input = driver.find_element(By.XPATH,
                                "//i/input")
    input.click()

    # 9. Click 'I1'
    i1 = driver.find_element(By.XPATH,
                             "//td[5]//i")
    i1.click()

    # 10. Click 'update_correo_usuario'
    update_correo_usuario = driver.find_element(By.CSS_SELECTOR,
                                                "#update_correo_usuario")
    update_correo_usuario.click()

    # 11. Type 'prc1@ucatolica.edu.co' in 'update_correo_usuario'
    update_correo_usuario = driver.find_element(By.CSS_SELECTOR,
                                                "#update_correo_usuario")
    update_correo_usuario.send_keys("prc1@ucatolica.edu.co")

    # 12. Click 'update_contrasena_usuario'
    update_contrasena_usuario = driver.find_element(By.CSS_SELECTOR,
                                                    "#update_contrasena_usuario")
    update_contrasena_usuario.click()

    # 13. Type '0123456789' in 'update_contrasena_usuario'
    update_contrasena_usuario = driver.find_element(By.CSS_SELECTOR,
                                                    "#update_contrasena_usuario")
    update_contrasena_usuario.send_keys("0123456789")

    # 14. Click 'Guardar Cambios'
    guardar_cambios = driver.find_element(By.XPATH,
                                          "//button[. = 'Guardar Cambios']")
    guardar_cambios.click()

    # 15. Click 'Iniciar Sesion1'
    iniciar_sesion1 = driver.find_element(By.XPATH,
                                          "//span[. = 'Iniciar Sesion']")
    iniciar_sesion1.click()

    # 16. Click 'login_nickname_usuario'
    login_nickname_usuario = driver.find_element(By.CSS_SELECTOR,
                                                 "#login_nickname_usuario")
    login_nickname_usuario.click()

    # 17. Type 'prc1' in 'login_nickname_usuario'
    login_nickname_usuario = driver.find_element(By.CSS_SELECTOR,
                                                 "#login_nickname_usuario")
    login_nickname_usuario.send_keys("prc1")

    # 18. Type '0123456789' in 'login_contrasena_usuario'
    login_contrasena_usuario = driver.find_element(By.CSS_SELECTOR,
                                                   "#login_contrasena_usuario")
    login_contrasena_usuario.send_keys("0123456789")

    # 19. Click 'INPUT'
    input = driver.find_element(By.XPATH,
                                "//i/input")
    input.click()

    # 20. Click 'I1'
    i1 = driver.find_element(By.XPATH,
                             "//td[5]//i")
    i1.click()

    # 21. Click 'update_correo_usuario'
    update_correo_usuario = driver.find_element(By.CSS_SELECTOR,
                                                "#update_correo_usuario")
    update_correo_usuario.click()

    # 22. Type 'prc1@gmail.com' in 'update_correo_usuario'
    update_correo_usuario = driver.find_element(By.CSS_SELECTOR,
                                                "#update_correo_usuario")
    update_correo_usuario.send_keys("prc1@gmail.com")

    # 23. Type '123456789' in 'update_contrasena_usuario'
    update_contrasena_usuario = driver.find_element(By.CSS_SELECTOR,
                                                    "#update_contrasena_usuario")
    update_contrasena_usuario.send_keys("123456789")

    # 24. Click 'Guardar Cambios'
    guardar_cambios = driver.find_element(By.XPATH,
                                          "//button[. = 'Guardar Cambios']")
    guardar_cambios.click()
